<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ric
 * Date: Wed, 30 Nov 2022 20:48:07 +0000
 */

$conf['title'] = 'Hacman Demo';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['defer_js'] = 0;
$conf['plugin']['commonmark']['force_commonmark'] = 1;
$conf['plugin']['indexmenu']['skip_file'] = '/(^sidebar$)/';
$conf['plugin']['syntaxhighlightjs']['syntax'] = 'code';
$conf['plugin']['syntaxhighlightjs']['theme'] = 'zenburn';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'custom';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'spacelab';
$conf['tpl']['bootstrap3']['customTheme'] = 'assets/custom/bootstrap.min.css';
$conf['tpl']['bootstrap3']['showWikiInfo'] = 0;
$conf['tpl']['bootstrap3']['useAvatar'] = 'gravatar';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['plugin']['loadskin']['automaticOutput'] = '1';
$conf['tpl']['mikio']['showLightDark'] = '1';
$conf['tpl']['mikio']['heroTitle'] = '0';
$conf['plugin']['syntaxhighlighter4']['theme'] = 'theme-midnight.css';
$conf['plugin']['syntaxhighlighter4']['override'] = 'code';
$conf['plugin']['mdpage']['markdown_default'] = '1';
$conf['tpl']['mindthedark']['theme'] = 'dark';
$conf['datadir'] = './data/gitrepo/wiki/pages';
$conf['mediadir'] = './data/gitrepo/wiki/media';
