# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 26 Nov 2022 00:40:58 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

hacmanadmin:$2y$10$uxIlgvl76bnwLOo0BPTOb.34zDt/dYkh8QHNpxvOgjSjuPPY6GQRW:admin:hacman@googlemail.com:admin,user
